development:
  adapter: mysql
  database: passwordly_development
  username: passwordly
  password: t3h_p4ssw0rdly

# These would be the settings for using sqlite:
#  adapter: sqlite3
#  database: db/development.sqlite3
#  timeout: 5000

test:
  adapter: mysql
  database: passwordly_development
  username: passwordly
  password: t3h_p4ssw0rdly

production:
  adapter: mysql
  database: passwordly_development
  username: passwordly
  password: t3h_p4ssw0rdly
